# Generated by Django 4.1.3 on 2022-11-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='choiceText',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='publicationDate',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='questionText',
        ),
    ]
